name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: cd Nurses-Academy-CBT-main && npm install

      - name: Build
        run: cd Nurses-Academy-CBT-main && DISABLE_ESLINT_PLUGIN=true react-scripts build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Nurses-Academy-CBT-main/build
